Add Abhishek singh information
iiitv/hacktoberfest21-web-gdsc-iiitv pull request #21
Opened 2021-10-04 14:11 UTC by 5-Abhi-5

Add details in data.json file

2021-10-04 14:28 UTC, nlok5923 requested changes
Thanks for PR PTAL !!

2021-10-04 14:28 UTC, nlok5923 commented on data.json
> +            },
@5-Abhi-5 you need to remove this "}" brances around your info

2021-10-05 04:10 UTC, nlok5923 requested changes
PTAL !!

2021-10-05 04:10 UTC, nlok5923 commented on data.json
> +
@5-Abhi-5 please remove the extra lines

2021-10-06 05:20 UTC, 5-Abhi-5 commented
Please review the changes

2021-10-06 07:53 UTC, 5-Abhi-5 commented
how to resolve merge conflicts

2021-10-06 11:03 UTC, nlok5923 approved these changes

2021-10-06 11:04 UTC, merged