add siddhant094 information
iiitv/hacktoberfest21-web-gdsc-iiitv pull request #26
Opened 2021-10-04 16:11 UTC by siddhant094

2021-10-04 16:43 UTC, nlok5923 requested changes
PTAL

2021-10-04 16:43 UTC, nlok5923 commented on data.json
> -      "github":"https://github.com/AkhileshManda",
@siddhant094 please revert all the unncessary changes.

2021-10-05 04:08 UTC, nlok5923 commented
@siddhant094 still there are lot of unnecessary changes do remove it.

2021-10-05 05:38 UTC, siddhant094 commented
@nlok5923 Yes, i will open another pr by evening , by that time I am closing this pr

2021-10-05 05:38 UTC, closed without merging